/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as UUsernameRouteRouteImport } from './routes/u.$username.route'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as UUsernameTaggedRouteImport } from './routes/u.$username.tagged'
import { Route as UUsernameSavedRouteImport } from './routes/u.$username.saved'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRouteRoute = UUsernameRouteRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameTaggedRoute = UUsernameTaggedRouteImport.update({
  id: '/tagged',
  path: '/tagged',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameSavedRoute = UUsernameSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => UUsernameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/$username': typeof UUsernameRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/u/$username/saved': typeof UUsernameSavedRoute
  '/u/$username/tagged': typeof UUsernameTaggedRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/u/$username/saved': typeof UUsernameSavedRoute
  '/u/$username/tagged': typeof UUsernameTaggedRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/$username': typeof UUsernameRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/u/$username/saved': typeof UUsernameSavedRoute
  '/u/$username/tagged': typeof UUsernameTaggedRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/u/$username'
    | '/auth/login'
    | '/auth/signup'
    | '/u/$username/saved'
    | '/u/$username/tagged'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/u/$username/saved'
    | '/u/$username/tagged'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/u/$username'
    | '/auth/login'
    | '/auth/signup'
    | '/u/$username/saved'
    | '/u/$username/tagged'
    | '/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UUsernameRouteRoute: typeof UUsernameRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/tagged': {
      id: '/u/$username/tagged'
      path: '/tagged'
      fullPath: '/u/$username/tagged'
      preLoaderRoute: typeof UUsernameTaggedRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/saved': {
      id: '/u/$username/saved'
      path: '/saved'
      fullPath: '/u/$username/saved'
      preLoaderRoute: typeof UUsernameSavedRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
  }
}

interface UUsernameRouteRouteChildren {
  UUsernameSavedRoute: typeof UUsernameSavedRoute
  UUsernameTaggedRoute: typeof UUsernameTaggedRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const UUsernameRouteRouteChildren: UUsernameRouteRouteChildren = {
  UUsernameSavedRoute: UUsernameSavedRoute,
  UUsernameTaggedRoute: UUsernameTaggedRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const UUsernameRouteRouteWithChildren = UUsernameRouteRoute._addFileChildren(
  UUsernameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UUsernameRouteRoute: UUsernameRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
